<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>index</title>
  <link rel="stylesheet" href="app/library/css/milligram.min.css">
  <link rel="stylesheet" href="app/library/css/normalize.min.css">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="site">
    <div class="grid-col just-center">
      <header class="order-1">
          <div class="container grid">
              <div class="g-col-1-2">
                  <div class="nav-left flex-row just-right">
                    <div class="cursor-pointer brg">
                      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                    </div>
                  </div>
              </div>
              <div class="g-col-1-3 flex-row">
                <div class="head-brand">
                  <h3>FIOPL</h3>
                </div>
              </div>
              <div class="g-col-3-12">
                  <div class="nav-left flex-row just-right white">
                    <div class="drop cursor-pointer">
                      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                      <sub>0</sub>
                    </div>
                    <div class="drop drop-down">
                      <svg class="w-6 h-6 cursor-pointer" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
                      <div class="drop-item small-drop absolute capital-letter font-size-12 italic pad-10">
                        <p class="cursor-pointer mar-pad-0 white">Profile demo</p>
                        <a href="user/log" class="cursor-pointer mar-pad-0 white">login demo</a>
                      </div>
                    </div>
                    <div class="drop cursor-pointer">
                      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"></path></svg>
                    </div>
                  </div>
              </div>
          </div>
      </header>
      <div class="dorp-down"></div>
    <main class="grid container">
      <aside class="pad-top-25 dis-b-n">
        <div class="aside-left pad-left-10">
          <div class="flex-col">
            <div class="nav-l">
              <h5 class="mar-pad-0">App</h5>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>All</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Windows</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Linux</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Mack</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Androed</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>iOS</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Server</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Others</span>
              </div>
            </div>
            <div class="nav-l">
              <h5 class="mar-pad-0">Languages</h5>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>All</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>HTML</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>C/C++</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>C#</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>JavaScript</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>PHP</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Python</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Java</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>GoLang</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Perl</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Others</span>
              </div>
            </div>
            <div class="nav-l">
              <h5 class="mar-pad-0">Framworks & Library</h5>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>All</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Wordpress</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Node.js</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Laravell</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>React</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Django</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Codeigniter</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>OpenCV</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Flask</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Flatter</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Others</span>
              </div>
            </div>
            <div class="nav-l">
              <h5 class="mar-pad-0">Departments</h5>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>eCommerce</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Education</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Blog / Magazine</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Entertanement</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Technology</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Corporate</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Portfoleo</span>
              </div>
              <div class="nav-check">
                <span for="all"><input type="checkbox" name="all" value="All" id=""></span>
                <span>Others</span>
              </div>
            </div>
          </div>
        </div>
      </aside>
      <article class="pad-5">
        <div class="flex-row just-center pad-top-25">
          <div class="card">
            <div class="card-body">
              <a class="flex-row just-center card-img">
                <img src="app/img/00_thumbnil.jpg" alt="">
              </a>
              <div class="card-title pad-5">
                <p class="mar-pad-0">By <span>Michel jackson</span> in <span>Login form HTML</span></p>
                <h6 class="mar-pad-0">Lorem - Lorem ipsom doller site multiple templetes multiple templetes</h6>
              </div>
              <div class="card-about flex-row just-center pad-5">
                <div class="order-1 card-price">
                  <h4><span>$</span><span>12</span></h4>
                </div>
                <div class="card-but order-2 ali-f-c flex-row just-right">
                  <a title="add to card">
                    <svg class="pad-5 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                  </a>
                  <a href="app/public/view.html" title="view">
                    <svg class="pad-5 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path></svg>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="paging flex-row just-center">
          <div class="pad-top-bot-25">
            <a class="button button-clear cursor-pointer">More</a>
          </div>
        </div>
      </article>
    </main>
    </div>
  </div>
</body>
</html>