<div class="aside-left pad-left-10">
                      <div class="flex-col">
                        <div class="nav-l">
                          <h5 class="mar-pad-0 font-size-15">
                            <span><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 w-h-18" viewBox="0 0 20 20" fill="currentColor">
                              <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                              <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
                            </svg></span>
                            <span class="pad-left-10">Dashbord</span>
                            <span class="pad-left-10">&#8250</span>
                          </h5>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <a href="/dashbord/index/" class="pad-left-10">Default</a>
                          </div>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <span class="pad-left-10">Analytics</span>
                          </div>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <span class="pad-left-10">CRM</span>
                          </div>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <span class="pad-left-10">Managemant</span>
                          </div>
                        </div>
                        <div class="nav-l">
                          <h5 class="mar-pad-0 font-size-15">
                            <span><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 w-h-18" viewBox="0 0 20 20" fill="currentColor">
                              <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                              <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
                            </svg></span>
                            <span class="pad-left-10">User</span>
                            <span class="pad-left-10">&#8250</span>
                          </h5>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <a href="/create" class="pad-left-10">Create</a>
                          </div>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <a href="/user/list/all-user" class="pad-left-10">List</a>
                          </div>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <span class="pad-left-10">CRM</span>
                          </div>
                          <div class="nav-check pad-left-10 font-size-15 pointer">
                            <span for="all">&#x269C</span>
                            <span class="pad-left-10">Managemant</span>
                          </div>
                        </div>
                      </div>
</div>