<div class="container grid">
                    <div class="g-col-1-2">
                        <div class="nav-left flex-row just-right">
                          <div class="cursor-pointer brg">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                          </div>
                        </div>
                    </div>
                    <div class="g-col-1-3 flex-row">
                      <div class="head-brand">
                        <h3>FIOPL</h3>
                      </div>
                    </div>
                    <div class="g-col-3-12">
                        <div class="nav-left flex-row just-right white">
                          <div class="drop cursor-pointer">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
                            <sub>0</sub>
                          </div>
                          <div class="bord drop drop-down">
                            <img class="w-h-20" src="../img/man5.jpg" alt="">
                            <div class="drop-item small-drop absolute capital-letter font-size-12 italic pad-10">
                              <p class="cursor-pointer mar-pad-0">Profile file</p>
                              <a href="/user/get/out" class="cursor-pointer mar-pad-0">log Out </a>
                            </div>
                          </div>
                          <div class="drop cursor-pointer">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"></path></svg>
                          </div>
                        </div>
                    </div>
</div>